stages:
  - build
  - test
  - cleanup

sonic-submodule:
  only:
    - merge_requests
    - api
    - web
  stage: build
  tags:
    - sonic
  script:
    - git grep '^<<<<<<< ' && echo "Conflicts exist--cannot build" && exit 1
    - echo ${CI_COMMIT_REF_NAME} | grep -q -e '^merge-[0-9][0-9][0-9][0-9]-' -e '^feature/MERGE-[0-9][0-9][0-9][0-9]-' && echo 'This is a sync--no build to do' && exit 0
    - env
    - du -hs .
    - rm -rf *
    - du -hs .
    - git clone -q ssh://git@gitlab.force10networks.com/e-sonic/sonic-buildimage.git
    - cd sonic-buildimage
    - git clone -q -b stable ssh://git@gitlab.force10networks.com/e-sonic/tools tools$$
    - export PLATFORM=broadcom
    - tools$$/submodule-code-review
